[repositories.Diagnostics-Custom-Device]
build_number = 10

[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 5

[repositories.J1939-Custom-Device]
build_number = 0

[repositories.Waveform-Processing-Custom-Device]
build_number = 1

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 2

[repositories.commonbuild-configuration]

[repositories.FPGA-Custom-Device]
build_number = 0

[repositories.Control-Custom-Device]
build_number = 0

[repositories.Data-Publishing-Service]
build_number = 2
