[repositories.Diagnostics-Custom-Device]
build_number = 10

[repositories.OPC-UA-Client-Custom-Device]
build_number = 4

[repositories.J1939-Custom-Device]
build_number = 3

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 25

[repositories.Control-Custom-Device]
build_number = 5

[repositories.VeriStand-steps-for-TestStand]
build_number = 19

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 6

[repositories.Instrument-Custom-Device]
build_number = 6

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 4

[repositories.FPGA-Custom-Device]
build_number = 18

[repositories.Scan-Engine-Custom-Device]
build_number = 2

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 27
