[repositories.Diagnostics-Custom-Device]
build_number = 8

[repositories.OPC-UA-Client-Custom-Device]
build_number = 4

[repositories.J1939-Custom-Device]
build_number = 8

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 30

[repositories.Control-Custom-Device]
build_number = 9

[repositories.VeriStand-steps-for-TestStand]
build_number = 74

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 4

[repositories.Engine-Simulation-Toolkit-Custom-Device]
build_number = 0

[repositories.Instrument-Custom-Device]
build_number = 5

[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 2

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 4

[repositories.FPGA-Custom-Device]
build_number = 18

[repositories.Scan-Engine-Custom-Device]
build_number = 3

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 34
