[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 5

[repositories.Waveform-Processing-Custom-Device]
build_number = 1

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 0

[repositories.commonbuild-configuration]
