[repositories.Fuel-Injector-Analysis-Addon]

[repositories.J1939-Custom-Device]

[repositories.commonbuild-configuration]

[repositories.FPGA-Custom-Device]
build_number = 6

[repositories.UDP-Data-Link-Custom-Device]
build_number = 24

[repositories.VeriStand-steps-for-TestStand]
build_number = 17

[repositories.Scan-Engine-Custom-Device]
build_number = 2

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 27
