[repositories.commonbuild-configuration]

[repositories.FPGA-Custom-Device]
build_number = 4

[repositories.UDP-Data-Link-Custom-Device]
release_branches = [ "master",]
build_number = 26

[repositories.VeriStand-steps-for-TestStand]
build_number = 16

[repositories.Scan-Engine-Custom-Device]
build_number = 2

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 5
