[repositories.Diagnostics-Custom-Device]
build_number = 12

[repositories.OPC-UA-Client-Custom-Device]
build_number = 4

[repositories.J1939-Custom-Device]
build_number = 18

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 32

[repositories.Control-Custom-Device]
build_number = 17

[repositories.VeriStand-steps-for-TestStand]
build_number = 118

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 6

[repositories.Engine-Simulation-Toolkit-Custom-Device]
build_number = 3

[repositories.Instrument-Custom-Device]
build_number = 11

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 15

[repositories.FPGA-Custom-Device]
build_number = 29

[repositories.Data-Publishing-Service]
build_number = 0

[repositories.Scan-Engine-Custom-Device]
build_number = 3

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 42

[repositories.Waveform-Data-Logger-Custom-Device]
build_number = 0
