[repositories.Diagnostics-Custom-Device]
build_number = 10

[repositories.OPC-UA-Client-Custom-Device]
build_number = 4

[repositories.SLSC-EDS-Plugin-Custom-Device]
build_number = 2

[repositories.J1939-Custom-Device]
build_number = 10

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 34

[repositories.Control-Custom-Device]
build_number = 13

[repositories.VeriStand-steps-for-TestStand]
build_number = 118

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 5

[repositories.Engine-Simulation-Toolkit-Custom-Device]
build_number = 1

[repositories.Instrument-Custom-Device]
build_number = 10

[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 9

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 9

[repositories.FPGA-Custom-Device]
build_number = 24

[repositories.Data-Publishing-Service]
build_number = 0

[repositories.Scan-Engine-Custom-Device]
build_number = 3

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 44

[repositories.Waveform-Data-Logger-Custom-Device]
build_number = 0
