[repositories.commonbuild-configuration]

[repositories.FPGA-Custom-Device]
build_number = 3

[repositories.UDP-Data-Link-Custom-Device]
release_branches = [ "master", "develop",]
build_number = 22

[repositories.VeriStand-steps-for-TestStand]
build_number = 11

[repositories.Scan-Engine-Custom-Device]
build_number = 2

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 6
