[repositories.Diagnostics-Custom-Device]
build_number = 8

[repositories.OPC-UA-Client-Custom-Device]
build_number = 4

[repositories.J1939-Custom-Device]
build_number = 8

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 26

[repositories.Control-Custom-Device]
build_number = 9

[repositories.VeriStand-steps-for-TestStand]
build_number = 64

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 4

[repositories.Instrument-Custom-Device]
build_number = 5

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 4

[repositories.FPGA-Custom-Device]
build_number = 18

[repositories.Scan-Engine-Custom-Device]
build_number = 3

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 28
