[repositories.Diagnostics-Custom-Device]
build_number = 19

[repositories.OPC-UA-Client-Custom-Device]
build_number = 12

[repositories.SLSC-EDS-Plugin-Custom-Device]
build_number = 6

[repositories.J1939-Custom-Device]
build_number = 28

[repositories.Waveform-Processing-Custom-Device]
build_number = 4

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 52

[repositories.Control-Custom-Device]
build_number = 22

[repositories.VeriStand-steps-for-TestStand]
build_number = 172

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 10

[repositories.Engine-Simulation-Toolkit-Custom-Device]
build_number = 6

[repositories.Instrument-Custom-Device]
build_number = 19

[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 19

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 18

[repositories.FPGA-Custom-Device]
build_number = 41

[repositories.Data-Publishing-Service]
build_number = 3

[repositories.Radio-Style-Workspace-Objects]
build_number = 1

[repositories.Scan-Engine-Custom-Device]
build_number = 4

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 47

[repositories.Waveform-Data-Logger-Custom-Device]
build_number = 0
