[repositories.commonbuild-configuration]

[repositories.FPGA-Custom-Device]
build_number = 4

[repositories.VeriStand-steps-for-TestStand]
build_number = 4

[repositories.Scan-Engine-Custom-Device]
build_number = 0

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 5
