[repositories.Diagnostics-Custom-Device]
build_number = 13

[repositories.OPC-UA-Client-Custom-Device]
build_number = 4

[repositories.SLSC-EDS-Plugin-Custom-Device]
build_number = 3

[repositories.J1939-Custom-Device]
build_number = 19

[repositories.Waveform-Processing-Custom-Device]
build_number = 3

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 35

[repositories.Control-Custom-Device]
build_number = 17

[repositories.VeriStand-steps-for-TestStand]
build_number = 165

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 7

[repositories.Engine-Simulation-Toolkit-Custom-Device]
build_number = 4

[repositories.Instrument-Custom-Device]
build_number = 13

[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 14

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 16

[repositories.FPGA-Custom-Device]
build_number = 33

[repositories.Data-Publishing-Service]
build_number = 2

[repositories.Scan-Engine-Custom-Device]
build_number = 4

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 45

[repositories.Waveform-Data-Logger-Custom-Device]
build_number = 0
