[repositories.Diagnostics-Custom-Device]
build_number = 69

[repositories.OPC-UA-Client-Custom-Device]
build_number = 14

[repositories.NI-XNET-Monitor-Custom-Device]
build_number = 8

[repositories.J1939-Custom-Device]
build_number = 41

[repositories.Waveform-Processing-Custom-Device]
build_number = 6

[repositories.PXImc-Custom-Device]
build_number = 0

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 29

[repositories.Control-Custom-Device]
build_number = 28

[repositories.VeriStand-steps-for-TestStand]
build_number = 118

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 11

[repositories.Engine-Simulation-Toolkit-Custom-Device]
build_number = 5

[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 28

[repositories.Instrument-Custom-Device]
build_number = 41

[repositories.Modbus-Custom-Device-v2]
build_number = 1

[repositories.Ghost-Bus-Addon]
build_number = 3

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 46

[repositories.FPGA-Custom-Device]
build_number = 34

[repositories.Data-Publishing-Service]
build_number = 11

[repositories.Radio-Style-Workspace-Objects]
build_number = 1

[repositories.Profile-Interpolation-Custom-Device]
build_number = 5

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 12

[repositories.Waveform-Data-Logger-Custom-Device]
build_number = 3
