[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 5

[repositories.commonbuild-configuration]

[repositories.VeriStand-steps-for-TestStand]
build_number = 60

[repositories.Data-Publishing-Service]
build_number = 0

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 7
