[repositories.Diagnostics-Custom-Device]
build_number = 15

[repositories.OPC-UA-Client-Custom-Device]
build_number = 4

[repositories.SLSC-EDS-Plugin-Custom-Device]
build_number = 7

[repositories.J1939-Custom-Device]
build_number = 22

[repositories.Waveform-Processing-Custom-Device]
build_number = 4

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 38

[repositories.Control-Custom-Device]
build_number = 18

[repositories.VeriStand-steps-for-TestStand]
build_number = 169

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 8

[repositories.Engine-Simulation-Toolkit-Custom-Device]
build_number = 6

[repositories.Instrument-Custom-Device]
build_number = 17

[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 16

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 18

[repositories.FPGA-Custom-Device]
build_number = 38

[repositories.Data-Publishing-Service]
build_number = 2

[repositories.Scan-Engine-Custom-Device]
build_number = 4

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 47

[repositories.Waveform-Data-Logger-Custom-Device]
build_number = 0
