[repositories.Diagnostics-Custom-Device]
build_number = 15

[repositories.OPC-UA-Client-Custom-Device]
build_number = 4

[repositories.J1939-Custom-Device]
build_number = 24

[repositories.commonbuild-configuration]

[repositories.UDP-Data-Link-Custom-Device]
build_number = 32

[repositories.Control-Custom-Device]
build_number = 19

[repositories.VeriStand-steps-for-TestStand]
build_number = 125

[repositories.Fuel-Injector-Analysis-Addon]
build_number = 8

[repositories.Engine-Simulation-Toolkit-Custom-Device]
build_number = 5

[repositories.Instrument-Custom-Device]
build_number = 16

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 21

[repositories.FPGA-Custom-Device]
build_number = 35

[repositories.Data-Publishing-Service]
build_number = 2

[repositories.Scan-Engine-Custom-Device]
build_number = 3

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 44

[repositories.Waveform-Data-Logger-Custom-Device]
build_number = 0
