[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 5

[repositories.Instrument-Custom-Device]
build_number = 1

[repositories.commonbuild-configuration]

[repositories.FPGA-Custom-Device]
build_number = 0

[repositories.UDP-Data-Link-Custom-Device]
build_number = 0

[repositories.VeriStand-steps-for-TestStand]
build_number = 62

[repositories.Data-Publishing-Service]
build_number = 0

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 9

[repositories.Waveform-Data-Logger-Custom-Device]
build_number = 0
