[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 4

[repositories.commonbuild-configuration]

[repositories.VeriStand-steps-for-TestStand]
build_number = 48

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 1
