[repositories.Diagnostics-Custom-Device]
build_number = 11

[repositories.OPC-UA-Client-Custom-Device]
build_number = 1

[repositories.Ballard-Arinc-429-Custom-Device]
build_number = 5

[repositories.J1939-Custom-Device]
build_number = 1

[repositories.Waveform-Processing-Custom-Device]
build_number = 1

[repositories.Ghost-Bus-Addon]
build_number = 0

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 6

[repositories.commonbuild-configuration]

[repositories.FPGA-Custom-Device]
build_number = 0

[repositories.Control-Custom-Device]
build_number = 1

[repositories.UDP-Data-Link-Custom-Device]
build_number = 0

[repositories.Data-Publishing-Service]
build_number = 2
