[repositories.commonbuild-configuration]

[repositories.FPGA-Custom-Device]
build_number = 3

[repositories.Scan-Engine-Custom-Device]
build_number = 1

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 1
