[repositories.Fuel-Injector-Analysis-Addon]
build_number = 0

[repositories.Diagnostics-Custom-Device]
build_number = 2

[repositories.OPC-UA-Client-Custom-Device]
build_number = 0

[repositories.J1939-Custom-Device]

[repositories.CAN-Frame-Protection-Custom-Device]
build_number = 4

[repositories.commonbuild-configuration]

[repositories.FPGA-Custom-Device]
build_number = 8

[repositories.UDP-Data-Link-Custom-Device]
build_number = 24

[repositories.Control-Custom-Device]
build_number = 0

[repositories.VeriStand-steps-for-TestStand]
build_number = 17

[repositories.Scan-Engine-Custom-Device]
build_number = 2

[repositories.Chassis-TimeSync-Custom-Device]
build_number = 27
